### ISSUE TITLE
`Warning: A component is changing an uncontrolled input to be controlled` error in NextJS after following readme

### ISSUE THREAD

**Issue by nikitavoloboev** [iway1/react-ts-form#7]
### Version Number

^1.0.6

### Steps to reproduce

Have repo here: https://github.com/nikitavoloboev/test/tree/main/next-13

Can run `pnpm i` and `pnpm run dev`.

Actual code with inputs here: https://github.com/nikitavoloboev/test/blob/main/next-13/pages/index.tsx

I am not sure what I am doing wrong but every time I try to write in the input boxes I get this error:

<img width="568" alt="image" src="https://user-images.githubusercontent.com/6391776/210365580-cf573a03-1af5-472b-8ab0-f6859df9ae9d.png">

I expanded on code that is in readme, perhaps I missed something? Repo was started from latest Next 13 starter.

Thank you.

### Expected behaviour

No warning in console.

### Relevant log output

```shell
A component is changing an uncontrolled input to be controlled. This is likely caused by the value changing from undefined to a defined value, which should not happen. Decide between using a controlled or uncontrolled input element for the lifetime of the component.
```
```

**Comment by iway1** [comment]
So this is a normal occurence when using rhf/react doesn't really have to do with the library.

The problem is that the first time you render your input, the value is undefined so React doesn't know the input is supposed to be controlled (b/c value is undefined). 

So when you type it goes from uncontrolled to controlled and react doesn't like that.

I will update the docs to make it more obvious how to avoid this, though. 😊

**Comment by iway1** [comment]
docs updated
